### ISSUE TITLE
Failed to read network interfaces.

### ISSUE THREAD

**Issue by hussamh10** [haroon96/Network-Packet-Classifier#1]
![image](https://user-images.githubusercontent.com/11413675/32993982-6ea876e8-cd82-11e7-8c38-fa5aa1aeb809.png)
When run from an admin cmd (Windows) using:
`java -jar Network Packet Classifier.jar`

**Comment by Haroon96** [comment]
The error is most likely because you don't have windump configured on your system. I have updated the README to explicitly state this requirement. You can follow the official instructions [here](https://www.winpcap.org/windump/install/default.htm) to configure your system.
